### ISSUE TITLE
Verbindung mit der OpenDTU wird nicht hergestellt

### ISSUE THREAD

**Issue by o0shojo0o** [o0shojo0o/ioBroker.opendtu#20]
Also bei OpenDTU habe ich die Version (SDK v4.4.3, Konfig 0.1.24, FirmgitHash 055eb3a). Was mir auffällt ist, dass ich über den Github Link für den Iobroker die OpenDTU Version v0.1.2 installiert bekomme, Du nutzt die v0.1.1. Ist das ggf. ein Problem? Ansonsten sind die ja doch überschaubaren Einstellungen identisch aber der Objektbaum leider leer =(

![image](https://user-images.githubusercontent.com/125746530/225626061-d7d0072c-fa16-49a9-a416-14f494eff68b.png)

![image](https://user-images.githubusercontent.com/125746530/225625689-ca6b8cba-8149-4c41-8956-3af5c13d5579.png)

![image](https://user-images.githubusercontent.com/125746530/225625764-fee5ce43-ca70-4bb6-8a5c-0170354dea89.png)

![image](https://user-images.githubusercontent.com/125746530/225625880-0a38df58-7053-408d-b1cb-1fcc0d8cfaab.png)

avialible steht auch auf false...

Ich mache vermutlich etwas falsch...

_Originally posted by @DPO99 in https://github.com/tbnobody/OpenDTU/discussions/700#discussioncomment-5333624_

**Comment by o0shojo0o** [comment]
Hi, welche Node Version läuft auf deinen System?

**Comment by DPO99** [comment]
Hi!, anbei mal ein Screenshot der Systeminfos:

![image](https://user-images.githubusercontent.com/125746530/225705703-12d3c730-7c0d-4540-9c42-0521ffad13a6.png)

Dass die Version v18.15.0 verfügbar ist habe ich soeben erst gesehen, löst diese ggf. das Problem?

**Comment by DPO99** [comment]
Das sollte passen, IP Adressen und Kennwörter schreibe ich immer nur händisch rein:

![image](https://user-images.githubusercontent.com/125746530/225707935-f94be774-90d1-44e7-b1e4-874964ae8a8e.png)

Über den seitlichen Menüpunkt klappt das ja alles wunderbar:

![image](https://user-images.githubusercontent.com/125746530/225708089-b2f2a8c0-a332-4fb4-888d-c54aa4ce5b80.png)

Ist es ein Problem, dass OpenDTU parallel via MQTT läuft? Oder kann es sein, dass ich das Übertragen der Objekte antriggern muss oder sollte die der Adapter alle automatisch in den Objekte Baum laden?

**Comment by o0shojo0o** [comment]
Hmmm… das sollte dann so laufen, MQTT stört da nicht.
Ich stehe grad etwas auf den Schlauch, warum er nicht bei dir will :(
Hast du noch weiter Einträge im Log?

**Comment by DPO99** [comment]
Keine neuen. Habe den Adapter gerade mal neu installiert und erhalte die üblichen Verdächtigten:

![image](https://user-images.githubusercontent.com/125746530/225711886-c68aebf3-7dca-40ec-8191-84a2bd1933b1.png)

Ich kann das Ding ja mal nen Tag laufen lassen und beobachten, obs noch weitere Fehler gibt.

**Comment by DPO99** [comment]
Stört es ihn ggf, dass es zwei Wechselrichter/Seriennummern gibt die bis dato noch keine echte Verbindung zum Wechselrichter hatten? 

Ansonsten fällt mir nur noch ein, dass in der OpenDTU Anmeldemaske ja auch der Benutzername "admin" benötigt wird. Berücksichtigt das der Adpater (aber höchstwarsch. tut er das, da ja OpenDTU bei vielen sicher identisch ist).

**Comment by o0shojo0o** [comment]
> Stört es ihn ggf, dass es zwei Wechselrichter/Seriennummern gibt die bis dato noch keine echte Verbindung zum Wechselrichter hatten?

Sollte eigentlich nicht, aber testen konnte ich das noch nicht da ich nur einen habe.

> Ansonsten fällt mir nur noch ein, dass in der OpenDTU Anmeldemaske ja auch der Benutzername "admin" benötigt wird. Berücksichtigt das der Adpater (aber höchstwarsch. tut er das, da ja OpenDTU bei vielen sicher identisch ist).

Der admin ist hardcodet da der in openDTU nicht änderbar ist.

**Comment by o0shojo0o** [comment]
Kannst du bitte den Adapter mal auf `Debug` stellen und den Adapter aus diesen Branche installieren? 
https://github.com/o0shojo0o/ioBroker.opendtu/tree/issues_20

**Comment by DPO99** [comment]
hab ich gemacht. Da war eine IP Adresse drin, die hab ich mal geschwärzt, weiß nicht wie kritisch die ist/war.

`2023-03-16 21:11:13.787 - info: opendtu.0 (55435) starting. Version 0.1.2 (non-npm: o0shojo0o/ioBroker.opendtu#issues_20) in /opt/iobroker/node_modules/iobroker.opendtu, node: v16.19.1, js-controller: 4.0.24
2023-03-16 21:11:13.823 - warn: opendtu.0 (55435) Please configure the Websoket connection!
2023-03-16 21:11:21.598 - info: host.iobroker stopInstance system.adapter.opendtu.0 (force=false, process=true)
2023-03-16 21:11:21.604 - info: opendtu.0 (55435) Got terminate signal TERMINATE_YOURSELF
2023-03-16 21:11:21.607 - info: opendtu.0 (55435) terminating
2023-03-16 21:11:21.609 - info: opendtu.0 (55435) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-03-16 21:11:21.659 - info: host.iobroker stopInstance system.adapter.opendtu.0 send kill signal
2023-03-16 21:11:22.160 - info: host.iobroker instance system.adapter.opendtu.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-03-16 21:11:24.700 - info: host.iobroker instance system.adapter.opendtu.0 started with pid 55451
2023-03-16 21:11:26.111 - debug: opendtu.0 (55451) Redis Objects: Use Redis connection: xxx.x.x.x:xxxx
2023-03-16 21:11:26.159 - debug: opendtu.0 (55451) Objects client ready ... initialize now
2023-03-16 21:11:26.162 - debug: opendtu.0 (55451) Objects create System PubSub Client
2023-03-16 21:11:26.164 - debug: opendtu.0 (55451) Objects create User PubSub Client
2023-03-16 21:11:26.199 - debug: opendtu.0 (55451) Objects client initialize lua scripts
2023-03-16 21:11:26.208 - debug: opendtu.0 (55451) Objects connected to redis: xxx.x.x.x:xxxx
2023-03-16 21:11:26.231 - debug: opendtu.0 (55451) Redis States: Use Redis connection: xxx.x.x.x:xxxx
2023-03-16 21:11:26.242 - debug: opendtu.0 (55451) States create System PubSub Client
2023-03-16 21:11:26.244 - debug: opendtu.0 (55451) States create User PubSub Client
2023-03-16 21:11:26.300 - debug: opendtu.0 (55451) States connected to redis: xxx.x.x.x:xxxx
2023-03-16 21:11:26.447 - info: opendtu.0 (55451) starting. Version 0.1.2 (non-npm: o0shojo0o/ioBroker.opendtu#issues_20) in /opt/iobroker/node_modules/iobroker.opendtu, node: v16.19.1, js-controller: 4.0.24
2023-03-16 21:11:26.482 - warn: opendtu.0 (55451) Please configure the Websoket connection!
2023-03-16 21:11:36.212 - info: host.iobroker stopInstance system.adapter.opendtu.0 (force=false, process=true)
2023-03-16 21:11:36.218 - info: opendtu.0 (55451) Got terminate signal TERMINATE_YOURSELF
2023-03-16 21:11:36.221 - info: opendtu.0 (55451) terminating
2023-03-16 21:11:36.223 - info: opendtu.0 (55451) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-03-16 21:11:36.275 - info: host.iobroker stopInstance system.adapter.opendtu.0 send kill signal
2023-03-16 21:11:36.794 - info: host.iobroker instance system.adapter.opendtu.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-03-16 21:11:39.316 - info: host.iobroker instance system.adapter.opendtu.0 started with pid 55467
2023-03-16 21:11:40.747 - debug: opendtu.0 (55467) Redis Objects: Use Redis connection: xxx.x.x.x:xxxx
2023-03-16 21:11:40.783 - debug: opendtu.0 (55467) Objects client ready ... initialize now
2023-03-16 21:11:40.786 - debug: opendtu.0 (55467) Objects create System PubSub Client
2023-03-16 21:11:40.787 - debug: opendtu.0 (55467) Objects create User PubSub Client
2023-03-16 21:11:40.814 - debug: opendtu.0 (55467) Objects client initialize lua scripts
2023-03-16 21:11:40.823 - debug: opendtu.0 (55467) Objects connected to redis: xxx.x.x.x:xxxx
2023-03-16 21:11:40.848 - debug: opendtu.0 (55467) Redis States: Use Redis connection: xxx.x.x.x:xxxx
2023-03-16 21:11:40.858 - debug: opendtu.0 (55467) States create System PubSub Client
2023-03-16 21:11:40.861 - debug: opendtu.0 (55467) States create User PubSub Client
2023-03-16 21:11:40.916 - debug: opendtu.0 (55467) States connected to redis: xxx.x.x.x:xxxx
2023-03-16 21:11:41.067 - info: opendtu.0 (55467) starting. Version 0.1.2 (non-npm: o0shojo0o/ioBroker.opendtu#issues_20) in /opt/iobroker/node_modules/iobroker.opendtu, node: v16.19.1, js-controller: 4.0.24
2023-03-16 21:11:41.265 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:41.267 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:41.278 - debug: opendtu.0 (55467) {"dtu":{"reachable":false}}
2023-03-16 21:11:42.380 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:42.380 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:43.439 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:43.441 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:44.531 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:44.531 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:45.659 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:45.661 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:46.783 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:46.784 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:47.910 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:47.910 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:49.039 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:49.040 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:50.073 - debug: opendtu.0 (55467) {"dtu":{"reachable":false}}
2023-03-16 21:11:50.105 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:50.106 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:51.193 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:51.195 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:52.312 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:52.313 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:53.440 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:53.441 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:54.566 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:54.567 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:55.694 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:55.695 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:56.735 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:56.736 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:57.845 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:57.846 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:11:58.974 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:11:58.975 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:00.103 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:00.104 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:00.117 - debug: opendtu.0 (55467) {"dtu":{"reachable":false}}
2023-03-16 21:12:01.221 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:01.222 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:02.245 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:02.246 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:03.372 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:03.374 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:04.499 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:04.500 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:05.625 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:05.626 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:06.751 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:06.752 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:07.877 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:07.878 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:09.008 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:09.009 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:10.137 - debug: opendtu.0 (55467) {"dtu":{"reachable":false}}
2023-03-16 21:12:10.161 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:10.161 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:11.256 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:11.257 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:12.383 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:12.384 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:13.510 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:13.511 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:14.536 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:14.537 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:15.663 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:15.664 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:16.788 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:16.790 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:17.924 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:17.925 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:19.039 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:19.040 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:20.069 - debug: opendtu.0 (55467) {"dtu":{"reachable":false}}
2023-03-16 21:12:20.093 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:20.093 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:21.189 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:21.190 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:22.318 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:22.319 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:23.443 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:23.444 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:24.569 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:24.570 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:25.695 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:25.695 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:26.822 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:26.823 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:27.948 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:27.949 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:29.074 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:29.075 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:30.120 - debug: opendtu.0 (55467) {"dtu":{"reachable":false}}
2023-03-16 21:12:30.143 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:30.144 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:31.225 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:31.226 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:32.351 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:32.352 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:33.481 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:33.481 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:34.513 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:34.513 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:35.545 - debug: opendtu.0 (55467) Error: Unexpected server response: 401
2023-03-16 21:12:35.545 - debug: opendtu.0 (55467) Start try again in 1 seconds...
2023-03-16 21:12:35.831 - info: host.iobroker "system.adapter.opendtu.0" disabled
2023-03-16 21:12:35.831 - info: host.iobroker stopInstance system.adapter.opendtu.0 (force=false, process=true)
2023-03-16 21:12:35.839 - info: opendtu.0 (55467) Got terminate signal TERMINATE_YOURSELF
2023-03-16 21:12:35.842 - info: opendtu.0 (55467) terminating
2023-03-16 21:12:35.843 - info: opendtu.0 (55467) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-03-16 21:12:35.897 - info: host.iobroker stopInstance system.adapter.opendtu.0 send kill signal
2023-03-16 21:12:36.390 - info: host.iobroker instance system.adapter.opendtu.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)`

**Comment by o0shojo0o** [comment]
Der openDTU antwortet mit
den http Fehlercode 401, das deutet darauf hin das ein falsches Passwort übergeben wurde.

**Comment by o0shojo0o** [comment]
Ach warte.. hast du für die Übersicht das Passwort aktiviert, wenn ja macht das mal für die Übersicht aus.

Das habe ich nämlich aktuell nicht vorgesehen!

**Comment by DPO99** [comment]
Also ich habe beides mal überprüft. Folgende Einstellung ist/war gesetzt:

![image](https://user-images.githubusercontent.com/125746530/225863085-113b0799-4bcf-406a-aa6b-9911288156b7.png)

Mein Passwort hatte tatsächlich ein Sonderzeichen ($) enthalten. Ich habe das mal entfernt und auf (12345678) geändert, bekomme aber trotzdem wieder die 401 =/.

Ich habe auch mal alle nicht aktiven WR entfernt. Leider selbes Ergebnis =/

<html>
<body>


2023-03-17 10:17:58.125 - debug: opendtu.0 (90440) Error: Unexpected server response: 401
--
2023-03-17 10:17:58.126 - debug: opendtu.0 (90440) Start try again in 1 seconds...
2023-03-17 10:17:58.137 - debug: opendtu.0 (90440) {"dtu":{"reachable":false}}
2023-03-17 10:17:59.240 - debug: opendtu.0 (90440) Error: Unexpected server response: 401
2023-03-17 10:17:59.240 - debug: opendtu.0 (90440) Start try again in 1 seconds...
2023-03-17 10:18:00.061 - debug: opendtu.0 (90440) {"dtu":{"reachable":false}}
2023-03-17 10:18:00.366 - debug: opendtu.0 (90440) Error: Unexpected server response: 401
2023-03-17 10:18:00.367 - debug: opendtu.0 (90440) Start try again in 1 seconds...
2023-03-17 10:18:01.495 - debug: opendtu.0 (90440) Error: Unexpected server response: 401
2023-03-17 10:18:01.497 - debug: opendtu.0 (90440) Start try again in 1 seconds...
2023-03-17 10:18:02.620 - debug: opendtu.0 (90440) Error: Unexpected server response: 401
2023-03-17 10:18:02.622 - debug: opendtu.0 (90440) Start try again in 1 seconds...
2023-03-17 10:18:03.746 - debug: opendtu.0 (90440) Error: Unexpected server response: 401


</body>
</html>

**Comment by o0shojo0o** [comment]
Das macht mich ja nu wild… ;) 
Vielleicht können wir uns ja mal im Discord treffen und das zusammen durchgehen?

**Comment by o0shojo0o** [comment]
Bei mir ist leider nichts angekommen.

**Comment by DPO99** [comment]
Die 2. Mail scheint auch nicht angekommen zu sein =(. Schreib mir gerne in Discord: Timo#7462

**Comment by nicomania** [comment]
Hallo zusammen, ich habe genau das gleiche Problem. Frisch installierter Adapter und auch OpenDTU ist auf dem ganz frischen Stand. Bei Start des Adapters ist available für einen ganz kurzen Moment TRUE und dann gleich FALSE. Passwort und IP habe ich mehrfach geprüft. Nebenher läuft mqtt problemlos. Auffällig ist, dass der rssi Wert scheinbar erfolgreich abgefragt wird, der Rest jedoch nicht. Read ohne Passwort ist aktiviert und das Passwort enthält keine Sonderzeichen.

![image](https://user-images.githubusercontent.com/35151132/226905254-d62b9676-5769-4a54-a5b9-004b5f37cf70.png)

![image](https://user-images.githubusercontent.com/35151132/226905532-48dd8699-00fb-4a44-aa20-785d721b2804.png)

![image](https://user-images.githubusercontent.com/35151132/226906271-cc736c5a-5595-469a-a8f8-1d9a4b2c5cd8.png)

**Comment by o0shojo0o** [comment]
Könnte noch mal einer von euch den Branche https://github.com/o0shojo0o/ioBroker.opendtu/tree/issues_20 installieren und den Log posten?

**Comment by DPO99** [comment]
Also in dieser Version bekomme ich den Adapter generell nicht zum laufen:

![image](https://user-images.githubusercontent.com/125746530/227010090-ee694e9c-bf67-465e-bb42-ac5270e1aaaa.png)

<html>
<body>


2023-03-22 20:04:01.444 - debug: opendtu.0 (131324) Redis Objects: Use Redis connection: 127.0.0.1:9001
--
2023-03-22 20:04:01.480 - debug: opendtu.0 (131324) Objects client ready ... initialize now
2023-03-22 20:04:01.483 - debug: opendtu.0 (131324) Objects create System PubSub Client
2023-03-22 20:04:01.484 - debug: opendtu.0 (131324) Objects create User PubSub Client
2023-03-22 20:04:01.508 - debug: opendtu.0 (131324) Objects client initialize lua scripts
2023-03-22 20:04:01.517 - debug: opendtu.0 (131324) Objects connected to redis: 127.0.0.1:9001
2023-03-22 20:04:01.541 - debug: opendtu.0 (131324) Redis States: Use Redis connection: 127.0.0.1:9000
2023-03-22 20:04:01.552 - debug: opendtu.0 (131324) States create System PubSub Client
2023-03-22 20:04:01.554 - debug: opendtu.0 (131324) States create User PubSub Client
2023-03-22 20:04:01.619 - debug: opendtu.0 (131324) States connected to redis: 127.0.0.1:9000
2023-03-22 20:04:01.775 - info: opendtu.0 (131324) starting. Version 0.1.2 (non-npm: o0shojo0o/ioBroker.opendtu#issues_20) in /opt/iobroker/node_modules/iobroker.opendtu, node: v16.19.1, js-controller: 4.0.24
2023-03-22 20:04:01.807 - error: opendtu.0 (131324) TypeError: this.adapter.debug is not a function
2023-03-22 20:04:01.810 - error: opendtu.0 (131324) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-03-22 20:04:01.811 - error: opendtu.0 (131324) unhandled promise rejection: Cannot read properties of undefined (reading 'on')
2023-03-22 20:04:01.814 - error: opendtu.0 (131324) TypeError: Cannot read properties of undefined (reading 'on')
at Opendtu.startWebsocket (/opt/iobroker/node_modules/iobroker.opendtu/main.js:136:18)
at Opendtu.onReady (/opt/iobroker/node_modules/iobroker.opendtu/main.js:45:14)
at Opendtu.emit (node:events:513:28)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8232:26
2023-03-22 20:04:01.815 - error: opendtu.0 (131324) Cannot read properties of undefined (reading 'on')
2023-03-22 20:04:01.860 - info: opendtu.0 (131324) terminating
2023-03-22 20:04:01.861 - warn: opendtu.0 (131324) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-03-22 20:04:02.410 - error: host.iobroker instance system.adapter.opendtu.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-22 20:04:02.410 - info: host.iobroker Restart adapter system.adapter.opendtu.0 because enabled


</body>
</html>

**Comment by o0shojo0o** [comment]
Ach misst hatte noch nen typo drinnen nochmal bitte :)

**Comment by o0shojo0o** [comment]
Ach jetzt sehe ich es erst .... 
Stelle das bitte mal so ein, da muss ich noch im Adapter nachbessern ..  
>
![image](https://user-images.githubusercontent.com/19333515/227161782-26d9c070-6ce0-4880-98c6-b67891a925a6.png)

**Comment by nicomania** [comment]
Bei mir funktioniert es damit auch. Danke!

**Comment by o0shojo0o** [comment]
> Jetzt funktioniert es =). Eine Frage hätte ich noch. Wie genau geht man denn mit PowerON PowerOFF und Restart um? Egal ob true oder false, da tut sich leider nix am WR. Das Limit setzen klappt problemlos.
> 
https://github.com/o0shojo0o/ioBroker.opendtu#014-2023-03-23
