### ISSUE TITLE
Unhandled exception leads to restart loop

### ISSUE THREAD

**Issue by indie89** [o0shojo0o/ioBroker.opendtu#34]
Hallo zusammen, ich hab ein Problem mit dem Adapter und sowohl die neueste Firmware von opendtu geflasht, als auch das passende node.js drauf und die aktuelle Adapter Installation drauf. Das Problem trat auch mit einer älteren Firmware Version von opendtu schon auf, ich hatte gehofft, dass es mit der neuen Version gelöst wäre, aber nach ca 18 Stunden Betrieb ging das ganze schon wieder los: nach einer Weile ganz normalem Betriebs wird im Adapter eine unhandled exception geworfen und der Adapter Gerät dann in eine "restart loop", sodass iobroker den Adapter killt, nachdem 4-5 Mal in 1,5 min neu gestartet wurde.
Das logfile zu dem Fehler im Adapter in iobroker ist folgendes (nur eine "Fehlerinstanz", diese tritt dann mehrfach nacheinander auf). 2 hinweise noch zur Fehler Eingrenzung:

Mqtt ist in opendtu aus, zufriff läuft über http.
Im Kontext des Fehlers verändern sich die Namen der 2 verbundenen wechselrichter in der Webansicht und enthalten plötzlich seltsame Sonderzeichen oder werden komplett durch solche ersetzt.
Ein Ansatz könnte sein, dass es einen overflow beim opendtu gibt, der zb durch nicht geschlossene web connections Auftritt und durch den Adapter ausgelöst wird?

Würde mich sehr freuen, wenn ich einen Tipp von euch bekomme oder mit der Fehlerbeschreibung die Weiterentwicklung des Adapters unterstützten kann 🙂
Vielen Dank!

2023-04-18 12:56:52.639 error The id is empty! Please provide a valid id.

opendtu.0
2023-04-18 12:56:52.638 error Error: The id is empty! Please provide a valid id. at Utils.validateId (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19) at Opendtu.extendObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:1935:23) at /opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2126:16 at new Promise (<anonymous>) at Opendtu.extendObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2125:16) at DataController.processInverterData (/opt/iobroker/node_modules/iobroker.opendtu/lib/dataController.js:23:36) at Opendtu.processMessage (/opt/iobroker/node_modules/iobroker.opendtu/main.js:163:28) at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.opendtu/main.js:142:18) at WebSocket.emit (node:events:525:35) at Receiver.receiverOnMessage (/opt/iobroker/node_modules/ws/lib/websocket.js:1184:20)

opendtu.0
2023-04-18 12:56:52.634 error unhandled promise rejection: The id is empty! Please provide a valid id.

opendtu.0
2023-04-18 12:56:52.616 error Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by o0shojo0o** [comment]
Hi habe ich das richtig verstanden? 
Auch im Webinterface von OpenDTU werden die Namen komisch dargestellt?

**Comment by indie89** [comment]
Hi, 
Ja genau! Gehe aktuell von der Reihenfolge "Adapter treibt die dtu in den Wahnsinn (mit irgendwelchen exceptions, zb eben nicht geschlossenen websockets etc), der dann vor lauter Verzweiflung die Namen korrumpiert" aus. Könnte theoretisch aber auch sein "aus irgendeinem Grund korrumpiert die dtu die Namen in der Laufzeit selbst und das bringt den Adapter ins stolpern, der dann die Fehler wirft". Wovon gehst du aus bzw falls es zweiteres ist, hättest du auch außerhalb deines Adapters (für den ich sehr dankbar bin) einen Tipp für mich, woran es dann liegen könnte?

**Comment by o0shojo0o** [comment]
Nein Laut deinen Log kommt keine gültige Serial mehr und deshalb kabelt es dann. 
Kann es sein das du deine DTU mit Kommands überforderst?

**Comment by indie89** [comment]
Ah okay. Meinst du mit serial die tatsächliche seriennummer der wr? Wie kann so eine "Überforderung mit commands" aussehen? Falls dazu eine relativ hohe Abfragefrequenz der wr werten durch die dtu bei gleichzeitig 2 angeschlossenen wr gehört, ist das möglich. Bin da gerade bei 2s, das könnte ich, wenn es das nächste Mal auftritt, einfach Mal ändern, und auf 10s. Oder meintest du mit commands was anderes?

**Comment by o0shojo0o** [comment]
Ja das z.B. oder auch Leistungsbegrenzungs Einstellungen.

**Comment by indie89** [comment]
Nee, über den Adapter lese ich bisher nur, da wird (noch) nichts geschrieben. Meinst du also, dass der esp32 einfach an seine Grenzen kommt und dann unvollständige Datensätze schickt?!?

**Comment by indie89** [comment]
Ich teste es morgen und sag bescheid.

**Comment by indie89** [comment]
Kurzes Update: nachdem ich in der dtu das refresh interval von 2s auf 5s gesetzt habe und jeder String einen Namen bekommen hat, tritt das Problem seit 30h schon nicht mehr auf. Ich gehe also davon aus, dass die dtu tatsächlich mit der Last überfordert war und der Fehler im Adapter durch fehlerhafte Übertragung von der dtu ausgelöst wurde. Ich entschuldige mich für die falsche Verdächtigung des Adapters und würde das issue schließen :-). Danke für die Hilfe!
